---
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Beam Docker Release
        uses: shortishly/beam-docker-release-action@5dc1d1d881375bbbfa288a18c04da66f6a02fca7
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          build-platforms: linux/amd64
          build-tags: ghcr.io/${{ github.repository }}:erlang.mk
