---
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Beam Docker Release
        uses: shortishly/beam-docker-release-action@c077df6ee37738c435f4f19d6a1b52d93ad14429
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          build-command: mix do local.hex --force + deps.get + local.rebar + release
          build-image: elixir:1.14.1
          build-platforms: linux/amd64
          build-tags: ghcr.io/${{ github.repository }}:elixir-phx
